# Generated by Django 4.0.6 on 2022-08-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavLink',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.DeleteModel(
            name='WorkProject',
        ),
    ]
