# Generated by Django 4.0.6 on 2022-10-20 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('img', models.FileField(upload_to='tmp/static/img/')),
                ('img_alt', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to='tmp/static/img/')),
                ('img_alt', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'compétence',
                'verbose_name_plural': 'compétences',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'réseau',
                'verbose_name_plural': 'réseaux sociaux',
            },
        ),
        migrations.CreateModel(
            name='WorkProject',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets pro',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job_title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='France', max_length=100)),
                ('dateFrom', models.DateField(default=django.utils.timezone.now)),
                ('dateTo', models.DateField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApi.workproject')),
            ],
            options={
                'verbose_name': 'expérience',
                'verbose_name_plural': 'expériences pro',
            },
        ),
    ]
