# Generated by Django 4.0.6 on 2022-08-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0002_alter_skill_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.FileField(upload_to='tmp/static/img/'),
        ),
    ]
