# Generated by Django 4.0.6 on 2022-08-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0003_alter_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlink',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
