# Generated by Django 4.0.6 on 2022-08-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0004_alter_navlink_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='navlink',
            table='une ancre',
        ),
    ]
