# Generated by Django 4.0.6 on 2022-08-31 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0005_alter_navlink_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navlink',
            options={'verbose_name': 'une ancre'},
        ),
        migrations.AlterModelTable(
            name='navlink',
            table=None,
        ),
    ]
