# Generated by Django 4.0.6 on 2022-08-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0007_alter_navlink_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'projet', 'verbose_name_plural': 'projets'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'compétence', 'verbose_name_plural': 'compétences'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'réseaux sociaux', 'verbose_name_plural': 'réseau'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'expérience', 'verbose_name_plural': 'expériences pro'},
        ),
        migrations.AlterModelOptions(
            name='workproject',
            options={'verbose_name': 'projet', 'verbose_name_plural': 'projets pro'},
        ),
    ]
