# Generated by Django 4.0.6 on 2022-08-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0008_alter_project_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'réseau', 'verbose_name_plural': 'réseaux sociaux'},
        ),
    ]
