# Generated by Django 4.0.6 on 2022-10-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0009_alter_sociallink_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='work',
            name='country',
            field=models.CharField(default='France', max_length=100),
        ),
    ]
